/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      1000,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6678",
            customMemoryMap:
           [          
                ["MSMC_SHARED", 
                     {
                        name: "MSMC_SHARED",
                        base: 0x0c000000,                    
                        len: 0x00080000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["L2SRAM", 
                     {
                        name: "L2SRAM",
                        base: 0x00800000,                    
                        len: 0x00040000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR3_SHARED", 
                     {
                        name: "DDR3_SHARED",
                        base: 0x80000000,                    
                        len: 0x40000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["MSMC", 
                     {
                        name: "MSMC",
                        base: 0x0c0c0000,                    
                        len: 0x00040000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR3", 
                     {
                        name: "DDR3",
                        base: 0xd8000000,                    
                        len: 0x08000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l2Mode: "256k",
          l1PMode: "32k",
          l1DMode: "32k",

    });
    
instance :
    
    override config string codeMemory  = "L2SRAM";   
    override config string dataMemory  = "MSMC";                                
    override config string stackMemory = "L2SRAM";

    config String l2Mode = "256k";
    config String l1PMode = "32k";
    config String l1DMode = "32k";
}
